[package]
name = "madome-users-schema"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sea-orm = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
